### ISSUE TITLE
Save File Issues 

### ISSUE THREAD

**Issue by nitishpatel** [salmanmkc/Java_Sharable-Film-List-Management-GUI#1]
While Saving the file there is no default file format mentioned while saving the file. 
As the widget being used in JTable I think only csv , excel file should be allowed.
I tried saving the file in .txt format 
Here is what I got  when I opened it
![Annotation 2020-03-25 011456](https://user-images.githubusercontent.com/39486276/77470050-12262300-6e36-11ea-9b74-584f6f14949d.png)

**Comment by salmanmkc** [comment]
It's a .DAT file which holds binray data, you open it with the Film Adder Program itself, it's not supposed to be used within other programs.

**Comment by salmanmkc** [comment]
It's a .DAT file which holds binray data, you open it with the Film Adder Program itself, it's not supposed to be used within other programs, you can open it with notepad even without saving it with .txt and it will give you the same result.
